Lab09/Lab09_Tasks/DemoEshop.PresentationLayer/Controllers/Admin/AdminCustomersController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using DemoEshop.BusinessLayer.DataTransferObjects;
using DemoEshop.BusinessLayer.DataTransferObjects.Filters;
using DemoEshop.BusinessLayer.Facades;
using X.PagedList;

namespace DemoEshop.PresentationLayer.Controllers.Admin
{
    public class AdminCustomersController : Controller
    {
        public CustomerFacade CustomerFacade { get; set; }
        public OrderFacade OrderFacade { get; set; }

        public async Task<ActionResult> Index(int page = 1)
        {
            var result = await CustomerFacade.GetAllCustomersAsync();
            var pageSize = result.TotalItemsCount > 0 ? (int)result.TotalItemsCount : 1;
            var model = new StaticPagedList<CustomerDto>(result.Items, page, pageSize, (int)result.TotalItemsCount);
            return View(model);
        }

        public async Task<ActionResult> Orders(Guid id)
        {
            var orders = await OrderFacade.GetOrdersAsync(new OrderFilterDto{ CustomerId = id });
            return View(orders);
        }

        public async Task<ActionResult> Details(Guid id)
        {
            var orderItems = await OrderFacade.ListItemsFromOrderAsync(new OrderItemFilterDto{ OrderId = id });
            return View(orderItems);
        }
    }
}

Lab09/Lab09_Tasks/DemoEshop.PresentationLayer/Controllers/Admin/AdminProductsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using DemoEshop.BusinessLayer.DataTransferObjects;
using DemoEshop.BusinessLayer.DataTransferObjects.Filters;
using DemoEshop.BusinessLayer.Facades;
using DemoEshop.PresentationLayer.Models.AdminProducts;
using X.PagedList;

namespace DemoEshop.PresentationLayer.Controllers.Admin
{
    public class AdminProductsController : Controller
    {
        public ProductFacade ProductFacade { get; set; }
        public OrderFacade OrderFacade { get; set; }

        public async Task<ActionResult> Index(int page = 1)
        {
            // TODO...

            throw new NotImplementedException();
        }
        
        public ActionResult Create()
        {
            // TODO...

            throw new NotImplementedException();
        }

        public async Task<ActionResult> Create(AdminProductEditModel model)
        {
            // TODO...

            throw new NotImplementedException();
        }

        public async Task<ActionResult> Edit(Guid id)
        {
            // TODO...

            throw new NotImplementedException();
        }

        public async Task<ActionResult> Edit(Guid id, AdminProductEditModel model)
        {
            // TODO...

            throw new NotImplementedException();
        }

        public async Task<ActionResult> Delete(Guid id)
        {
            // TODO...

            throw new NotImplementedException();
        }
    }
}

Lab09/Lab09_Tasks/DemoEshop.PresentationLayer/Views/Shared/_Layout.cshtml
@using DemoEshop.PresentationLayer.Helpers.Cookies
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Demo Eshop</title>
    @RenderSection("head", required: false)
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-dark bg-dark navbar-expand-md fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Demo Eshop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="navbar-toggler-icon" />
            </button>
            <div class="navbar-collapse collapse">
                <ul class="navbar-nav mr-auto">
                    @if (User.IsInRole("Administrator"))
                    {
                        <li class="nav-item">@Html.ActionLink("Products", "Index", "AdminProducts", new { @class = "nav-link" })</li>
                        <li class="nav-item mr-auto">@Html.ActionLink("Customers", "Index", "AdminCustomers", new { @class = "nav-link" })</li>
                    }
                    else
                    {
                        <li class="nav-item mr-auto">@Html.ActionLink("Products", "Index", "Products", new { @class = "nav-link" })</li>
                    }
                </ul>
                <ul class="navbar-nav">
                    @if (!this.ViewContext.RouteData.Values["controller"].ToString().Equals("ShoppingCart"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="/ShoppingCart">
                                <span class="fa fa-shopping-cart" style="margin-right: 5px;"></span>
                                @{
                                    var shoppingItemsCount = Request.GetAllShoppingCartItems("daisy@gmail.com").Count;
                                    if (shoppingItemsCount > 0)
                                    {
                                        <span class="label label-default label-pill "> @shoppingItemsCount items</span>
                                    }
                                }
                            </a>
                        </li>
                    }
                    @if (Request.IsAuthenticated)
                    {
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-item dropdown-toggle" data-toggle="dropdown"><span class="fa fa-user"></span> @User.Identity.Name.Split('@')[0] <b class="caret grey"></b></a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <div class="dropdown-header">Account management</div>
                                <div class="dropdown-divider"></div>
                                @Html.ActionLink("Logout", "Logout", "Account", new { @class = "dropdown-item" })
                            </div>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" id="dropdownMenuLink" data-toggle="dropdown"><span class="fa fa-user"></span><b class="caret grey"></b></a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                                <div class="dropdown-header">Get started</div>
                                <div class="dropdown-divider"></div>
                                @Html.ActionLink("Register", "Register", "Account", new { @class = "dropdown-item" })
                                <div class="dropdown-divider"></div>
                                @Html.ActionLink("Log in", "Login", "Account", new { @class = "dropdown-item" })
                            </div>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-muted float-right">&copy; @DateTime.Now.Year created by Martin Macák & Jaroslav Davídek</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Styles.Render("~/css/font-awesome.min.css")
    @RenderSection("scripts", required: false)
</body>
</html>