Lab10/Lab10_Solution/DemoEshop.PresentationLayer/Models/Products/ProductListViewModel.cs
using System.Collections.Generic;
using System.Web.Mvc;
using DemoEshop.BusinessLayer.DataTransferObjects;
using DemoEshop.BusinessLayer.DataTransferObjects.Filters;
using X.PagedList;

namespace DemoEshop.PresentationLayer.Models.Products
{
    public class ProductListViewModel
    {
        public string[] ProductSortCriteria => new[]{nameof(ProductDto.Name), nameof(ProductDto.Price), nameof(ProductDto.DiscountPercentage) };

        public IList<CategoryDto> Categories { get; set; }

        public IPagedList<ProductDto> Products { get; set; }

        public ProductFilterDto Filter { get; set; }

        public SelectList AllSortCriteria => new SelectList(ProductSortCriteria);
    }
}

Lab10/Lab10_Solution/DemoEshop.PresentationLayer/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using DemoEshop.BusinessLayer.DataTransferObjects;
using DemoEshop.BusinessLayer.DataTransferObjects.Common;
using DemoEshop.BusinessLayer.DataTransferObjects.Filters;
using DemoEshop.BusinessLayer.Facades;
using DemoEshop.PresentationLayer.Models.Products;
using X.PagedList;

namespace DemoEshop.PresentationLayer.Controllers
{
    public class ProductsController : Controller
    {
        #region SessionKey constants

        public const int PageSize = 9;

        private const string FilterSessionKey = "filter";
        private const string CategoryTreesSessionKey = "categoryTrees";

        #endregion

        #region Facades

        public ProductFacade ProductFacade { get; set; }

        #endregion

        #region ProductsActionMethods

        public async Task<ActionResult> Index(int page = 1)
        {
            var filter = Session[FilterSessionKey] as ProductFilterDto ?? new ProductFilterDto{ PageSize = PageSize};
            filter.RequestedPageNumber = page;
            var result = await ProductFacade.GetProductsAsync(filter);

            var categoryTrees = Session[CategoryTreesSessionKey] as IList<CategoryDto>;
            var model = await InitializeProductListViewModel(result, categoryTrees);
            return View("ProductListView", model);
        }

        [HttpPost]
        public async Task<ActionResult> Index(ProductListViewModel model)
        {
            model.Filter.PageSize = PageSize;
            model.Filter.CategoryIds = ProcessCategoryIds(model);
            Session[FilterSessionKey] = model.Filter;
            Session[CategoryTreesSessionKey] = model.Categories;

            var result = await ProductFacade.GetProductsAsync(model.Filter);
            var newModel = await InitializeProductListViewModel(result, model.Categories);
            return View("ProductListView", newModel);
        }

        public ActionResult ClearFilter()
        {
            Session[FilterSessionKey] = null;
            Session[CategoryTreesSessionKey] = null;
            return RedirectToAction(nameof(Index));
        }

        public async Task<ActionResult> Details(Guid id)
        {
            var model = await ProductFacade.GetProductAsync(id);
            return View("ProductDetailView", model);
        }

        #endregion

        #region Helper methods

        /// <summary>
        /// Initializes new ProductListViewModel according to its parameters
        /// </summary>
        /// <param name="result">Product list query result containing products page and related data</param>
        /// <param name="categories">List of category trees</param>
        /// <returns>Initialized instance of ProductListViewModel</returns>
        private async Task<ProductListViewModel> InitializeProductListViewModel(QueryResultDto<ProductDto, ProductFilterDto> result, IList<CategoryDto> categories = null)
        {
            return new ProductListViewModel
            {
                Products = new StaticPagedList<ProductDto>(result.Items, result.RequestedPageNumber ?? 1, PageSize, (int)result.TotalItemsCount),
                Categories = categories ?? await ProductFacade.GetAllCategories() as IList<CategoryDto>,
                Filter = result.Filter
            };
        }

        /// <summary>
        /// Processes category IDs by filtering out unchecked categories
        /// </summary>
        /// <param name="model">model containing category trees</param>
        /// <returns>selected categories</returns>
        private static Guid[] ProcessCategoryIds(ProductListViewModel model)
        {
            var selectedCategoryIds = new List<Guid>();
            foreach (var categoryTreeRoot in model.Categories)
            {
                if (categoryTreeRoot.IsActive)
                {
                    selectedCategoryIds.Add(categoryTreeRoot.Id);
                    selectedCategoryIds.AddRange(model.Categories
                        .Where(node => node.ParentId == categoryTreeRoot.Id && node.IsActive)
                        .Select(node => node.Id));
                }                
            }
            return selectedCategoryIds.ToArray();
        } 
        
        #endregion
    }
}

Lab10/Lab10_Solution/DemoEshop.PresentationLayer/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using DemoEshop.BusinessLayer.DataTransferObjects;
using DemoEshop.BusinessLayer.Facades;
using DemoEshop.PresentationLayer.Helpers.Attributes;
using DemoEshop.PresentationLayer.Helpers.Cookies;
using DemoEshop.PresentationLayer.Models.ShoppingCart;

namespace DemoEshop.PresentationLayer.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        #region ConfigurationProperties

        private const int DefaultShoppingItemQuantity = 1;

        private DateTime RefreshedExpiration => DateTime.Now.AddMinutes(ShoppingCartCookieManager.CookieExpirationInMinutes); 
        
        #endregion

        #region Facades

        public CustomerFacade CustomerFacade { get; set; }

        public OrderFacade OrderFacade { get; set; }

        public ProductFacade ProductFacade { get; set; }

        #endregion
        
        #region ShoppingCartItemsListActionMethods

        public async Task<ActionResult> Index()
        {
            var model = await CreateShoppingCartViewModel();
            return View("ShoppingItemsListView", model);
        }

        public async Task<ActionResult> AddItem(Guid id)
        {
            var product = await ProductFacade.GetProductAsync(id);
            var model = await CreateShoppingCartViewModel();

            // if item for the requested product is already in the shopping cart, take no action  
            if (model.ShoppingCartItems.Any(item => item.Product.Equals(product)))
            {
                return RedirectToAction("Index");
            }

            if (await TryReserveStock(model.Customer, product))
            {
                model.ShoppingCartItems.Add(new OrderItemDto
                {
                    Product = product,
                    Quantity = DefaultShoppingItemQuantity
                });
                Response.SaveAllShoppingCartItems(User.Identity.Name, model.ShoppingCartItems);
            }

            return RedirectToAction("Index");
        }
    
        public async Task<ActionResult> ClearAllItems()
        {
            var customer = await CustomerFacade.GetCustomerAccordingToUsernameAsync(User.Identity.Name);
            Response.ClearAllShoppingCartItems(User.Identity.Name);
            OrderFacade.ReleaseReservations(customer.Id);
            return RedirectToAction("Index", "Products");
        }

        [HttpPost]
        [MultiPostAction(Name = "action", Argument = "SaveAndContinueShopping")]
        public async Task<ActionResult> SaveAndContinueShopping(ShoppingCartViewModel model)
        {
            await SaveAllShoppingCartItems(model);
            return RedirectToAction("Index", "Products");
        }

        [HttpPost]
        [MultiPostAction(Name = "action", Argument = "Proceed")]
        public async Task<ActionResult> Proceed(ShoppingCartViewModel model)
        {
            await SaveAllShoppingCartItems(model);
            var newModel = await CreateShoppingCartViewModel(model.ShoppingCartItems);
            return View("ShoppingCartCheckoutView", newModel);
        }

        #endregion

        #region CheckoutActionMethods

        [HttpPost]
        [MultiPostAction(Name = "action", Argument = "ConfirmOrder")]
        public async Task<ActionResult> ConfirmOrder(ShoppingCartViewModel model)
        {
            var createOrderDto = await CreateOrderCreateViewModel();

            await OrderFacade.ConfirmOrderAsync(createOrderDto, () => Response.ClearAllShoppingCartItems(User.Identity.Name));

            var orderConfirmModel = await CreateOrderConfirmationViewModel(createOrderDto);

            return View("OrderConfirmation", orderConfirmModel);
        }

        #endregion

        #region HelperMethods

        private async Task SaveAllShoppingCartItems(ShoppingCartViewModel model)
        {
            var customer = await CustomerFacade.GetCustomerAccordingToUsernameAsync(User.Identity.Name);
            foreach (var item in model.ShoppingCartItems)
            {
                if (item.Quantity == 0)
                {
                    OrderFacade.ReleaseReservations(customer.Id, item.Product.Id);
                    continue;
                }

                if (!await TryReserveStock(customer, item.Product, item.Quantity))
                {
                    await RetryStockReservation(item, customer);
                }   
            }
            var itemsToSave = model.ShoppingCartItems.Where(item => item.Quantity > 0);
            Response.SaveAllShoppingCartItems(User.Identity.Name, itemsToSave);
        }

        #region StockReservationMethods

        private async Task<bool> TryReserveStock(CustomerDto customer, ProductDto product, int? desiredQuantity = null)
        {
            var reservation = new ProductReservationDto
            {
                CustomerId = customer.Id,
                ProductId = product.Id,
                ReservedAmount = desiredQuantity ?? DefaultShoppingItemQuantity,
                Expiration = RefreshedExpiration
            };
            var isReservationSuccessfull = await OrderFacade.ReserveProductAsync(reservation);
            return isReservationSuccessfull;
        }

        private async Task RetryStockReservation(OrderItemDto item, CustomerDto customer)
        {
            var maxAvailableUnits = await OrderFacade.GetCurrentlyAvailableUnitsAsync(item.Product.Id);
            if (maxAvailableUnits > 0)
            {
                item.Quantity = maxAvailableUnits;
                await TryReserveStock(customer, item.Product, maxAvailableUnits);
            }
        }

        #endregion

        #region ViewModelCreationMethods

        /// <summary>
        /// Creates ShoppingCartViewModel
        /// </summary>
        /// <param name="shoppingCartItems">Items in the shopping cart</param>
        /// <returns>ShoppingCartViewModel</returns>
        private async Task<ShoppingCartViewModel> CreateShoppingCartViewModel(IList<OrderItemDto> shoppingCartItems = null)
        {
            return new ShoppingCartViewModel
            {
                Customer = await CustomerFacade.GetCustomerAccordingToUsernameAsync(User.Identity.Name),
                ShoppingCartItems = shoppingCartItems ?? Request.GetAllShoppingCartItems(User.Identity.Name),
                TotalPrice = OrderFacade.CalculateTotalPrice(shoppingCartItems)
            };
        }

        /// <summary>
        /// Creates OrderConfirmationViewModel
        /// </summary>
        /// <param name="createOrderDto">ViewModel containing data about order creation</param>
        /// <returns>OrderConfirmationViewModel</returns>
        private async Task<OrderConfirmationViewModel> CreateOrderConfirmationViewModel(OrderCreateDto createOrderDto)
        {
            return new OrderConfirmationViewModel
            {
                Customer = await CustomerFacade.GetCustomerAccordingToUsernameAsync(User.Identity.Name),
                Order = createOrderDto.OrderDto
            };
        }

        /// <summary>
        /// Creates OrderCreateViewModel
        /// </summary>
        /// <returns>OrderCreateViewModel</returns>
        private async Task<OrderCreateDto> CreateOrderCreateViewModel()
        {
            var newModel = await CreateShoppingCartViewModel();
            
            var order = new OrderDto
            {
                CustomerId = newModel.Customer.Id,
                Issued = DateTime.Now,
                TotalPrice = OrderFacade.CalculateTotalPrice(newModel.ShoppingCartItems)
            };

            return new OrderCreateDto
            {
                OrderDto = order,
                OrderItems = newModel.ShoppingCartItems
            };
        }

        #endregion

        #endregion
    }
}

Lab10/Lab10_Solution/DemoEshop.PresentationLayer/Views/Products/ProductDetailView.cshtml
@using DemoEshop.BusinessLayer.DataTransferObjects.Enums
@model DemoEshop.BusinessLayer.DataTransferObjects.ProductDto

@{
    ViewBag.Title = "ProductDetailView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-4">
        <img src="@Model.ProductImgUri" class="img-fluid">
    </div>
    <div class="col-sm-8">
        <h3>@Html.DisplayFor(model => model.Name)</h3>

        <div class="row text-justify top-buffer-small col-sm-12">@Html.DisplayFor(model => model.Description)</div>

        <div class="row top-buffer-small col-sm-12">
            @{
                if (Model.DiscountPercentage > 0)
                {
                    <div class="row">
                        <div class="col-sm-4">
                            <span>Former price: <strong class="text-danger"><del>@Model.Price.ToString("N2"),- CZK</del></strong></span>
                        </div>
                        <div class="col-sm-2">
                            <p>
                                <span>Discount: <strong class="text-success">@Model.DiscountPercentage%</strong></span>
                            </p>
                        </div>
                    </div>
                }
                else
                {
                    if (Model.DiscountType == DiscountType.Quantity3Plus1)
                    {
                        <div class="row container">
                            <div class="col-md-12">
                                <p>
                                    Buy 3x @Model.Name for
                                    <strong class="text-primary">@Model.Price.ToString("N2"),- CZK </strong>
                                    and get next one for
                                    <strong class="text-success">FREE</strong>
                                </p>
                            </div>
                        </div>
                    }
                    else
                    {
                        <div class="row container">
                            <div class="col-md-12">
                                <p>
                                    <strong class="text-primary">@Model.Price.ToString("N2"),- CZK</strong>
                                </p>
                            </div>
                        </div>
                    }

                }
            }
        </div>

        <div class="row top-buffer-small">
            @{
                if (Model.CurrentlyAvailableUnits.HasValue && Model.CurrentlyAvailableUnits.Value > 0)
                {
                    <div class="col-sm-8">
                        <span>Available units: <strong class="text-success">@Model.CurrentlyAvailableUnits</strong></span>
                    </div>
                    <div class="col-sm-4">
                        <input type="button" class="btn btn-primary" value="Add to shopping cart" onclick="location.href = '@Url.Action("AddItem", "ShoppingCart", new {id = Model.Id})'" />
                    </div>
                }
                else
                {
                    <div class="col-md-12">
                        <strong class="text-danger">No units are currently available</strong>
                    </div>
                }
            }
        </div>

        <p>
            @Html.ActionLink("Back to all products", "Index")
        </p>
    </div>
</div>

Lab10/Lab10_Solution/DemoEshop.PresentationLayer/Views/Products/ProductListView.cshtml
@using System.Web.Mvc.Html
@using X.PagedList.Mvc
@model DemoEshop.PresentationLayer.Models.Products.ProductListViewModel

@{
    ViewBag.Title = "ProductListView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section head{
    @Styles.Render("~/Content/css/tree.css")
    @Styles.Render("~/Content/css/PagedList.css")
    @Styles.Render("~/Content/themes/base/jquery-ui.css")
}

<div class="row">
    <div class="col-md-3">
        <div class="panel-heading panel-head">Categories</div>
        @using (Html.BeginForm())
        {

            <div class="tree">
                @for (var i = 0; i < Model.Categories.Count; i++)
                {
                    if (Model.Categories[i].HasParent)
                    {
                        continue;
                    }
                    <ul>
                        <li>
                            <a href="#">
                                @Html.CheckBoxFor(model => model.Categories[i].IsActive, new { @class = "tree-checkbox parent", @id = @Model.Categories[i].Id })
                                @Html.HiddenFor(model => model.Categories[i].Id)
                                @Html.HiddenFor(model => model.Categories[i].Name)
                                @Html.HiddenFor(model => model.Categories[i].ParentId)
                                <label for=@i>
                                    @Html.DisplayFor(model => model.Categories[i].Name)
                                </label>
                            </a>

                            <ul>
                                @for (var j = 0; j < Model.Categories.Count; j++)
                                {
                                    if (!Model.Categories[j].HasParent || Model.Categories[j].ParentId != Model.Categories[i].Id)
                                    {
                                        continue;
                                    }
                                    @Html.HiddenFor(model => model.Categories[j].Id)
                                    @Html.HiddenFor(model => model.Categories[j].Name)
                                    @Html.HiddenFor(model => model.Categories[j].ParentId)
                                    <li>
                                        <a href="#">
                                            @Html.CheckBoxFor(model => model.Categories[j].IsActive, new { @class = "tree-checkbox node-item", @iid = i + "" + j })

                                            <label for=@i@j>
                                                @Html.DisplayFor(model => model.Categories[j].Name)
                                            </label>
                                        </a>
                                    </li>

                                }
                            </ul>
                        </li>
                    </ul>
                }
            </div>

            <div class="form-group text-center">
                <b>
                    Price: <span id="spanOutput"></span>
                </b>
                <div id="slider" class="justify-content-center "></div>
                <input id="txtMin" type="hidden" name="Filter.MinimalPrice" />
                <input id="txtMax" type="hidden" name="Filter.MaximalPrice" />
            </div>
            <br />

            <div class="form-group form-row col-md-12">
                @Html.LabelFor(model => model.Filter.SearchedName, "Product Name", new { @class = "col-form-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Filter.SearchedName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Filter.SearchedName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group form-row col-md-12">
                @Html.LabelFor(model => model.Filter.SortCriteria, "Sort by:", new { @class = "col-form-label col-md-4" })
                <div class="col-md-8">
                    @Html.DropDownListFor(model => model.Filter.SortCriteria, Model.AllSortCriteria, "Select...", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Filter.SortCriteria, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-check form-row">
                @Html.LabelFor(model => model.Filter.SortAscending, "Ascending", new { @class = "form-check-label" })
                @Html.CheckBoxFor(model => model.Filter.SortAscending, new { htmlAttributes = new { @class = "form-check-input" } })
                @Html.ValidationMessageFor(model => model.Filter.SortAscending, "", new { @class = "text-danger" })
            </div>

            <div class="row btn-toolbar justify-content-around" role="toolbar" style="margin-bottom:5px">
                <div class="btn-group">
                    <input type="button" class="btn btn-danger" value="Clear" onclick="resetRange();location.href = '@Url.Action("ClearFilter", "Products")'" />
                </div>
                <div class="btn-group">
                    <button class="btn btn-success" id="btnSubmit" type="submit" onclick="saveRange()">Filter </button>
                </div>
            </div>

        }

        <div class="row justify-content-center">
            @Html.PagedListPager(Model.Products, page => Url.Action("Index", new { page }), new PagedListRenderOptions
       {
           LiElementClasses = new string[] { "page-item" },
           PageClasses = new string[] { "page-link" }
       })
        </div>
    </div>

    <div class="col-md-9">
        <div class="card-deck mb-3 text-center">
            @{foreach (var product in Model.Products)
                {
                    <div class="col-md-4 d-flex py-2">
                        <div class="card clickable-area" @("onclick=GoToDetail('" + product.Id + "')")>
                            <div class="d-flex justify-content-end">
                                @if (product.CurrentlyAvailableUnits.HasValue && product.CurrentlyAvailableUnits.Value > 0)
                                {
                                    <span class="badge badge-info badge-pill">@product.CurrentlyAvailableUnits.Value units</span>
                                }
                                else
                                {
                                    <span class="badge badge-danger disabled badge-pill">N/A</span>
                                }
                            </div>
                            <img src="@product.ProductImgUri" class="card-img-top" style="width:100%; height: 15vw;" alt="Product image">
                            <div class="card-body">
                                <h5 class="card-title" style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap;" id="thumbnail-label">@product.Name</h5>
                                <div class="caption text-center"></div>
                                @{
                                    if (product.DiscountPercentage > 0)
                                    {
                                        <div class="row">
                                            <div class="col-md-9 col-sm-9 col-xs-9">
                                                <strong class="text-danger"><del>@product.Price.ToString("N2"),- CZK</del></strong>
                                            </div>
                                            <div class="col-md-3 col-sm-3 col-xs-3">
                                                <p class="text-success">
                                                    <strong>@product.DiscountPercentage%</strong>
                                                </p>
                                            </div>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="row container">
                                            <div class="col-md-12">
                                                <p>
                                                    <strong class="text-primary">@product.Price.ToString("N2"),- CZK</strong>
                                                </p>
                                            </div>
                                        </div>
                                    }
                                }
                                <p class="card-text" style="height: 80px; width: 100%; overflow: hidden; text-overflow: ellipsis; white-space: normal; text-align: justify;">
                                    @product.Description
                                </p>
                                @if (product.CurrentlyAvailableUnits.HasValue && product.CurrentlyAvailableUnits.Value > 0)
                                {
                                    <input type="button" class="btn btn-primary" value="Add to shopping cart" onclick="location.href = '@Url.Action("AddItem", "ShoppingCart", new {id = product.Id})'" />
                                }
                                else
                                {
                                    <input type="button" class="btn btn-danger disabled" value="Out of stock" />
                                }
                            </div>
                        </div>
                    </div>
                }}
        </div>
    </div>
</div>

<script>
    function GoToDetail(id) {
        window.location = "/Products/Details/" + id;
    }
</script>

@section scripts{
    @Scripts.Render("~/Scripts/tree.js")
    @Scripts.Render("~/Scripts/jquery-ui-1.12.1.js")
    @Scripts.Render("~/Scripts/slider.js")
}